# Guess the Ramdome number generated by the program

import random
 
user_range = int(input("Enter Range Number ->  ")) 
randomNumber = random.randint(0, user_range)
print(randomNumber)

while True:
    user_guess = int(input("Make a Guess -> "))
    if user_guess == randomNumber:
        print("Good One ")
        break
    else:print("Try Again")
    